### ISSUE TITLE
Tripwires don't activate channel

### ISSUE THREAD

**Issue by Onoitsu2** [WirelessRedstoneGroup/WirelessRedstone#118]
I have been messing with tripwire in every way possible, and have come to the conclusion that this will not work with Wireless Redstone, in its current state. Even running redstone to the sign, or having it on top of a block that a moment ago I tested for conductivity with redstone on top of it, will not trigger the transmitter sign. I would love to add an alert system against trespassers, and would rather not use a million pressure plates when a little string could be used.

**Comment by Onoitsu2** [comment]
I would add the suggestion label, however it will not allow me to, only an admin for the issues board can apparently. Sorry :)

**Comment by Bart-0110** [comment]
I'll take a look into it tomorrow

**Comment by Bart-0110** [comment]
Mojang has changed the way that redstone work. This made it hard to make WirelessRedstone work in 1.8

E.g.
TBHss**S**ssHB

T = Transmitter
B = Block
H = Tripwire Hook
s = String
**S** = String where the player stands on

Explanation:
If the player walk on **S** the server only sends an event to that location. In the past it would send an event to every string and to every tripwire hook attached to the string. If we want to add the events manually then it will cause some serious server load/lagg. E.g. There are 50 people on the server who are free roaming over some strings, then the server needs to check all the strings everytime someone walks on a new string.

Solution:
Put a redstone wire nest to the block that is attached to the tripwire hook then put a transmitter next to it.

**Comment by Onoitsu2** [comment]
Even with there only being one piece of string and the hooks being as close as possible, it does not pick up any of the redstone power through either block. However I found a work around, a piece of redstone wire between the block and the transmitter sign will get it to trigger. This truly means it is not reading any redstone power coming to the block, but you can dig a block out under either block holding the tripwire, and place a piece of redstone wire, and then adjacent to this place the sign, and bury it.

![image](https://cloud.githubusercontent.com/assets/4420175/9334563/a9d20f34-458c-11e5-8671-cbd650a44a54.png)

**Comment by Onoitsu2** [comment]
Also, I have tested it with a lengthy string (10 or 11, I forget), it works in this way. Almost like a t-flop, or shorted out redstone machine, how it fizzles and flickers the power but turns on.
