### ISSUE TITLE
can't destroy block & database errors

### ISSUE THREAD

**Issue by harm27** [WirelessRedstoneGroup/WirelessRedstone#141]
Hey,

In my server i can't destroy some blocks who previous had a wireless redstone sign on it.
I destroyed the sign and the channel is removed, but i still can't destroy the block.

Harm27

**Comment by harm27** [comment]
Also, i have serveral server errors:
http://pastebin.com/Df0T0vXq
Something with database table is locked.

**Comment by Bart-0110** [comment]
That's weird. Do you run it on a local machine or on a host?

**Comment by harm27** [comment]
We are running it on our testserver. It is a copy of our main server. 
When we copy the wireless redstone plugin map from our main server to our test server, the main server is running. 
Can that be the problem?

**Comment by Bart-0110** [comment]
Yes. The file is locked if you copy it while it's running

**Comment by harm27** [comment]
Oke, then i will try it again when our main server is offline.

**Comment by harm27** [comment]
We have tried this, and using the file from the admin backup function.
Both give the same exception.
Is it possible that some tables become locked after a server crash?
And is there a way to fix that?

**Comment by Bart-0110** [comment]
Hmmm. Maybe, can you sent me your DB file?

**Comment by harm27** [comment]
The people who are above me in rank on the server don't want it. 
Because of the risk that somebody can get our db file and our map and then start a server with our map.

**Comment by Bart-0110** [comment]
Okey. After all you can try to switch to YML. Maybe that helps

**Comment by harm27** [comment]
Okey, that i can try. Is there a easy way to switch to YML, delete old database file en then switch back to database.

**Comment by Bart-0110** [comment]
Run /wra convert yml
In-game

**Comment by harm27** [comment]
And how the other way back to sqlite?

**Comment by harm27** [comment]
I tried it. 
I converted it to yml and then back to sqlite. 
Only i still get database table locked exception.
So the conversion didn't fixed it.

**Comment by Bart-0110** [comment]
Hello, harm27.
Sorry for the late response.
Are there any hidden files or any file that is called journal?
I think you closed the server incorrect and now the database is locked or it is a hard drive issue

**Comment by Bart-0110** [comment]
Hey, can you try this new beta version?

https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v3.0.0-beta
