### ISSUE TITLE
Fuel consumption

### ISSUE THREAD

**Issue by Pocketkid2** [WirelessRedstoneGroup/WirelessRedstone#146]
This feature would make it cost to use wireless redstone, you would setup a chest or something that would contain fuel items, and when the redstone signal is on, and transmitting, it would take items from that chest periodically. The fuel would be consumed at the beginning of the cycle to prevent problems, but for the special signs this could be changed. For example, a simple transmitter channel would have a chest full of redstone dust, and when a user flips a lever and the receiver turns into a turn, immediately a redstone dust is taken and another is taken every 5 seconds.

**Comment by Bart-0110** [comment]
Maybe I'll add it in the future but not right now.
