### ISSUE TITLE
Exception from metrics

### ISSUE THREAD

**Issue by Zardozon** [WirelessRedstoneGroup/WirelessRedstone#161]
Every time my world auto-saves my console gets the following error from WRS:

10.11 16:32:06 [Server] WARN [WirelessRedstone] Plugin WirelessRedstone v2.6.5 generated an exception while executing task 25 
10.11 16:32:06 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player; 
10.11 16:32:06 [Server] INFO at net.licks92.WirelessRedstone.Metrics.postPlugin(Metrics.java:335) ~[?:?] 
10.11 16:32:06 [Server] INFO at net.licks92.WirelessRedstone.Metrics.access$400(Metrics.java:57) ~[?:?] 
10.11 16:32:06 [Server] INFO at net.licks92.WirelessRedstone.Metrics$1.run(Metrics.java:223) ~[?:?] 
10.11 16:32:06 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-latest.jar:git-Spigot-de459a2-51263e9] 
10.11 16:32:06 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-latest.jar:git-Spigot-de459a2-51263e9] 
10.11 16:32:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92] 
10.11 16:32:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92] 
10.11 16:32:06 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

Server is running Spigot 1.10.2
Tried disabling metrics with no difference in outcome

**Comment by jackmawer** [comment]
Until this is fixed, a temporary workaround is using [Console Spam Fix](https://www.spigotmc.org/resources/console-spam-fix.18410/) from the Spigot project page.

**Comment by Bart-0110** [comment]
Thank you, looking into it

**Comment by Bart-0110** [comment]
@Zardozon can you tell me what command/action your console performs?

**Comment by Zardozon** [comment]
Each time the server saves/auto saves it generates the error.

**Comment by Bart-0110** [comment]
Yes but what does it do? Does it /save-all or something different?

**Comment by Zardozon** [comment]
I can't believe I answered with that. I'm sorry... 

It doesn't actually let me know which command it's running (hosted through Bisect Hosting), it just says "Saving world..." and then generates that error. As far as I know there are no other commands that run at that time. I downgraded for now to lose the error but I'll run the latest version again after work and see if I can get it to show up any other ways.

**Comment by jackmawer** [comment]
It's probably running `save-on` and then `save-all` - that's the default action MultiCraft panels use to save the world.

**Comment by Zardozon** [comment]
Okay, so I re-updated the plugin to 2.6.5 and ran it again. Manually running the save-on and save-all commands do nothing but it offset the time that the auto-save happened and so now it's no longer happening at the same time but it still generates the error exactly every 15 minutes. I'll attach my config file just in case.

[config.txt](https://github.com/licks92/WirelessRedstone/files/587403/config.txt)

**Comment by Zardozon** [comment]
Updated client to 1.11 and plugin to 2.6.7 and the issue is gone.
