### ISSUE TITLE
Spigot 1.11 Class cast exception on redstone event.

### ISSUE THREAD

**Issue by RealmportalMC** [WirelessRedstoneGroup/WirelessRedstone#163]
http://pastebin.com/i2aWPk8R
console spams with this error.
Plugin works otherwise.

Plugin version 2.6.7

Spigot 1.11 Latest as of Sunday Nov 27 6:30 PM CST

**Comment by RealmportalMC** [comment]
My bad it appears as if the jar didnt update correctly
Ignore this -_- i got it working

**Comment by Bart-0110** [comment]
Okey, Good it is solved. Do you still have the corrupted jar? Maybe I can add a check or something to tell you if the download is corrupted

**Comment by RealmportalMC** [comment]
no i mean the spigot.jar didnt get replaced. idk why but its not related to the plugin. sorry for any inconvienience

**Comment by Bart-0110** [comment]
Oh okay good to know.
