### ISSUE TITLE
Receiver as switch, with copied sign

### ISSUE THREAD

**Issue by wapjoe** [WirelessRedstoneGroup/WirelessRedstone#166]
Hello and thanks to this great plugin!

My english is not the best, i hope u understand me... ;-)

I use WR (2.6.7) at a spigot/bukkit-server (latest version, updated today), MC 1.11.

If i copy&paste (CTRL + middle mousebutton (wheel)) a sign as receiver with switch-function it looks good at first (see screenshot1). But if i activate the tranceiver, the sign will be switched from [switch] to [default] (see screenshot2).

It's the same if i generate the sign with /give, only if i create the sign manualy, it will works.
Screenshot1:
![2016-12-11_18 24 09](https://cloud.githubusercontent.com/assets/24509200/21082035/0cd919c6-bfd3-11e6-8ee4-e355c6f12d22.jpg)

Screenshot2:
![2016-12-11_18 24 22](https://cloud.githubusercontent.com/assets/24509200/21082049/5b1a3f0c-bfd3-11e6-98b6-bc89a6668b5c.jpg)

It's the same with [inverter] and maybe [clock] (i didt'n try clock for it).

Is this a bug at WR or in bukkit or in MC? May you know a way to fix this Problem? I try to build a big project and it's easier to copy&paste the signs. ;-)

Thanks für your support!

wapjoe

**Comment by wapjoe** [comment]
@Bart-0110 
May you have any ideas?

**Comment by Bart-0110** [comment]
Is the sign registered when you place it or when you right click it?

**Comment by wapjoe** [comment]
Only after right click

**Comment by Bart-0110** [comment]
Can you try [this](https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v3.0.0-beta) version?

**Comment by wapjoe** [comment]
Wow it looks great, it works with this beta! May it's possible to register the sign directly after placing, without right click?

I will try the beta and try out to give you a responce when i find a new bug! :-)

Thanks a lot!

**Comment by wapjoe** [comment]
May you can realise it as an option, like "AutoRegisterSigns: true/false"?
