### ISSUE TITLE
Old game logic (not working)

### ISSUE THREAD

**Issue by Fast2Angel** [WirelessRedstoneGroup/WirelessRedstone#174]
Hello

I have a Problem by Version 1.11
I have 1 Receiver [Receiver] test and 2 Transmitter [Transmitter] test.
I had 2 Transmitter in the kitchen to make the light at the one corner and to make the other corner out. This unfortunately does not work anymore.

Left Corner On [transmitter], [Receiver] light ist Aktivated, and the Rigth Corner [Transmitter] Does not turn off the light.

by the Older version is this Working =(

i hope you can Help me, Sorry for my Bad Englisch

**Comment by Bart-0110** [comment]
> Version 1.11

That version is heavily outdated, please update the plugin

Diese Version ist stark veraltet, bitte aktualisieren Sie das Plugin.
(Danke Google Übersetzer)

**Comment by Fast2Angel** [comment]
I have Minecraft Bukkit Version 1.11.2
And your Plugin WirelessRedstone v3.0.3

Thats not old??
Sorry 4 Understanding

**Comment by wapjoe** [comment]
Hi @Fast2Angel ,

you have to set the receiver as a switch, e.g.:

Sign for receiver:
[wrr]
test
[switch]
(empty)

Sign for the transmitter:
[wrt]
test
(empty)
(empty)

Now the both transmitter switch the light on/off, but its better to take buttons for the both transmitter.

**Comment by Fast2Angel** [comment]
![2017-02-13_21 58 39](https://cloud.githubusercontent.com/assets/25698779/22903427/d46138ba-f238-11e6-91f7-ca66af9d1c74.png)

Ok thanks for your Tip.
Unfortunately this does not work either.

I can only on and off with 1 switch, with the other does not go unfortunately.

Thanks for Helping.

**Comment by wapjoe** [comment]
I mean it so:
![github-wr](https://cloud.githubusercontent.com/assets/24509200/22903591/6bc6244a-f239-11e6-80d4-9ad76488694e.png)

**Comment by Fast2Angel** [comment]
Buttons ok tahts working, Switch or lever is not Working =(


2017-02-13 22:12 GMT+01:00 wapjoe <notifications@github.com>:

**Comment by wapjoe** [comment]
With 2 switch it will works too, but you need a bigger circuit and it's a bit complicated. Better take buttons ;-)

**Comment by Fast2Angel** [comment]
by my older server 1.6.4 is this working =(, this version is me to old.
i have Updatet to 1.11.2 and in this version is thats not more so Easy.
Ok, then I have to live with it.

thanks 4 Helping

2017-02-13 22:20 GMT+01:00 wapjoe <notifications@github.com>:

**Comment by wapjoe** [comment]
No problem! ;-)

**Comment by wapjoe** [comment]
@Bart-0110 can you closed this thread, please?

**Comment by Fast2Angel** [comment]
The plugin still does not work as before.
It was easier then

**Comment by Bart-0110** [comment]
Ah, I see it now. You want to have to old redstone logic (mechanics) back. There should be an option to do so.

Go to the config and change this
`gateLogic: OR`
to
`gateLogic: IGNORE`

**Comment by Fast2Angel** [comment]
Yes thats Working =D
**Yehaaaaaaaaaaaaaaaaaaaaaaaaaaaaa**
you are my Hero.

Ok Close

**Comment by wapjoe** [comment]
> Ah, I see it now. You want to have to old redstone logic (mechanics) back. There should be an option to do so.

Nice to know!
