### ISSUE TITLE
Error while hooking worldedit

### ISSUE THREAD

**Issue by Tyfcho** [WirelessRedstoneGroup/WirelessRedstone#176]
Version Plugin: v3.0.3? (In Console v2.6.1, in the plugin.yml 3.0.3)
Screenshot: https://gyazo.com/231a0bccdde13839bee019e2ebb8566f
Is up to date but says it's not?

**Comment by Bart-0110** [comment]
Seems like replacing the file failed. Can you try to redownload the file then stop the server and then move the plugin to the plugins folder.

**Comment by Tyfcho** [comment]
Already tried to do that, but it fails every time...

**Comment by Bart-0110** [comment]
Try stop the server, remove WirelessRedstone.jar, start the server, stop the server, place the newest version of WirelessRedstone into the plugins folder.

**Comment by Bart-0110** [comment]
Which version of WorldEdit do you have installed?

**Comment by Tyfcho** [comment]
5.5.8
