### ISSUE TITLE
High server load on block (sign) break

### ISSUE THREAD

**Issue by herm1ne** [WirelessRedstoneGroup/WirelessRedstone#177]
Hi  
I got the high server load when someone removes sign.  
The TPS will drop like 5-6 open block break whereas TPS is 19-20 normally.  

Could you look into this?  
Timings are attached for your reference.  
https://timings.spigotmc.org/?url=bakofuvulu  
https://timings.spigotmc.org/?url=yidihetowa

**Comment by Bart-0110** [comment]
Do you have a plugin which updates a lot of blocks at the same time?

**Comment by Bart-0110** [comment]
Can you re-upload the timings? And if you can can you do it with paperspigot instead of spigot because that has a better timings feature.
