### ISSUE TITLE
Channeless Signs

### ISSUE THREAD

**Issue by karai17** [WirelessRedstoneGroup/WirelessRedstone#180]
I recall some years ago Wireless Redstone used to have various intermediary objects such as delays, logic gates, etc that you could pass a signal into that allowed for a lot of flexibility when designing circuits. An example of this would be that I always liked to make lighthouses where only one side of the light was on at any given time, making it seem like a light was spinning around. I would make it like this:

* T = Transmitter
* R = Receiver
* C = Clock
* D = Delay
* L = Light

```
          L
          |
          D4000
          |
L--D3000--RC--D1000--L              T
          |
          D2000
          |
          L
```

Currently, delays and clocks are only attached to receivers so there is no way to build the aforementioned lighthouse or other similar applications, at least that I can see. Would it be possible to decouple functionality from receivers, or have both built-in and stand-alone functions (clock, delay..)?

**Comment by karai17** [comment]
After further research, the mod I used to use was [RedstoneChips](https://github.com/eisental/RedstoneChips). It's been inactive for several years.. I was wondering if some of the functionality might be able to be merged into this mod?

**Comment by Bart-0110** [comment]
Thank you for the suggestion, I'll look into it.
