### ISSUE TITLE
Wireless redstone Doesn't work

### ISSUE THREAD

**Issue by Marnix2904** [WirelessRedstoneGroup/WirelessRedstone#190]
the plugin does not work we have downloaded it several times on new ones but it still does not work with the spigot version 3.0.5 our server version is 1.12

**Error:**
1. [Server] INFO Enabling WirelessRedstone v3.0.5
2. [Server] ERROR Error occurred while enabling WirelessRedstone v3.0.5 (Is it up to date?)

**Comment by wapjoe** [comment]
Did you try the latest version of the Minecraft server? Latest is 1.12.2, but it shouldn't be the reason. What's your OS? When do you restart the server, do you see the folder WirelessRedstone in the folder plugins?
The server has rights to read and write?

Sorry my English is not the best^^

**Comment by Marnix2904** [comment]
yes, we did, and the folder is also there

Sorry my English is also not the best^^

**Error:**

18.02 15:01:49 [Server] INFO at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) ~[spigot12.jar:git-Spigot-ede465d-bb4ae3b]
18.02 15:01:49 [Server] INFO at org.sqlite.core.NativeDB.load(NativeDB.java:56) ~[spigot12.jar:git-Spigot-ede465d-bb4ae3b]
18.02 15:01:49 [Server] INFO at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[spigot12.jar:git-Spigot-ede465d-bb4ae3b]
18.02 15:01:49 [Server] INFO at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:308) ~[spigot12.jar:git-Spigot-ede465d-bb4ae3b]
18.02 15:01:49 [Server] INFO at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:272) ~[spigot12.jar:git-Spigot-ede465d-bb4ae3b]
18.02 15:01:49 [Server] INFO at java.lang.System.load(System.java:1086) ~[?:1.8.0_151]
18.02 15:01:49 [Server] INFO at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_151]
18.02 15:01:49 [Server] INFO at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_151]
18.02 15:01:49 [Server] INFO at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_151]
18.02 15:01:49 [Server] INFO at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_151]
18.02 15:01:49 [Server] INFO java.lang.NoClassDefFoundError: org/sqlite/NativeDB
18.02 15:01:49 [Server] ERROR Error occurred while enabling WirelessRedstone v3.0.5 (Is it up to date?)

**Comment by wapjoe** [comment]
Hi again^^

What is your Server-OS (Windows or Linux)? How do you start the Minecraft-server and witch *.jar you use also? Witch plugins do you have install too?

My Server OS is Linux (Ubuntu 16.04) and I install a Windows 10 based server today, with Java version 1.8.0_161 (64 bit). It works with both Server. 

Maybe you have to reinstall your Server?!

**Comment by Bart-0110** [comment]
It seems that you have a Minecraft server file/version that we do not support.

Please use Spigot (or a flavour of it).
