### ISSUE TITLE
Error when placing signs "characters not allowed in a channel name"

### ISSUE THREAD

**Issue by scoobydoofus** [WirelessRedstoneGroup/WirelessRedstone#193]
Hi, I'm running a 1.12.2 Spigot server with Wireless Redstone, and when I try to place a sign (either transmitter or receiver) I get error:

`[WirelessRedstone] The sign contains characters that are not allowed in a channel name.`

This happens no matter what channel name I try and I can successfully place a sign using the the command `/wrt <channelname>` so it's clear the characters I'm using aren't actually the problem.

I've tried disabling other plugins and resource packs, and the problem is the same.

Am I doing something wrong? When I place a sign, in the first line I put [wrt] or [transmitter] and then on the second line I put my channel name, I leave the other lines blank (have also tried putting some values in there but I still get errors).

Thanks!

**Comment by scoobydoofus** [comment]
Hey thanks for the quick reply.

No special characters, for example if I just use "test" it gives me the error, but if I use the same channel name with the /wrt command it works fine.

**Comment by wapjoe** [comment]
How do you create the signs?
This is how you create a simple sign:
1. Row: [wrr] (for receiver) / [wrt] (for transceiver)
2. Row: Test123

Can you find the channel in WirelessRedstoneDatabase.db? You can open the *.db-file for example with "DB Browser for SQLite Portable" (https://portableapps.com/apps/development/sqlite_database_browser_portable).

**Comment by scoobydoofus** [comment]
Yeah that's exactly what I'm doing, and it prompts the error about characters not allowed.

Like I said, I can successfully create a working transmitter and receiver using the commands in the terminal, and if I remove those signs it tells me that the channel has been deleted because there are no signs linked to it any more, so that side of things seems to work ok.

I'll check the database file tomorrow but I don't expect the channel to be in the database if it's telling me that the channel name is not valid.

**Comment by wapjoe** [comment]
Hi,
what happens if you set the signs once in creative mode and once in survival mode? If you set a sign with `/wrr Test123"`, copy it (press CTRL + mouse wheel) and paste it in another place?

Do you play as operator or normal user? Have you possibly configured a plugin for permissions? Do you set the shield (`/wrr Test123`) over the ingame terminal or an external console?

Please insert the content of config.yml here.
