### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by lolerdelol** [WirelessRedstoneGroup/WirelessRedstone#194]
hello guys can you help me whit a problem of serversign and wirlessredstone: i will try to explain it on by best english ;) but it is a little bit abstractive so it's hard to explain. But i will do my best! :)
so i created a themepark on minecraft. I downloaded serversigns,,wirlessredstone, traincarts. When i make the sign: [wrr] spawn
and i type in my text bar: /svs add /wr activate spawn 50 and i click on enter they say: Succesfully. When i click on the pc mouse (right button) on the sign whit: spawn cars (the cars for my attraction) they spawn but the sign whit [wrr] spawn disappear. And when i click another time it doen't work. Because the sign is gone. 
I hope you can help me! 
Thanks!

**Comment by Bart-0110** [comment]
Is there an error log in the console? If there isn't can you enable debug mode in the settings and see if there is an error log.
