### ISSUE TITLE
[1.13.2 BUG] Wall signs are not working.

### ISSUE THREAD

**Issue by DeveloperBoy** [WirelessRedstoneGroup/WirelessRedstone#198]
Hello there,

I've a problem with the latest 1.13 release of WirelessRedstone (beta).

When I create a wallsign, the rotation of it itsn't correct. See the pictures:
**After creating it:**
![alt text](https://i.ibb.co/gwBXjrp/voor.png "Before")

**After toggling it:**
![alt text](https://i.ibb.co/kx9wdV9/na.png "After")

Can you fix this please?

Thanks in advance!

Kind regards,
Stijn

**Comment by Bart-0110** [comment]
Hello,

The latest beta should have this fixed.
[Here is a link to the latest beta.](https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.0-beta.2)
