### ISSUE TITLE
1.13.2 Bug - Transmitter Signs not working.

### ISSUE THREAD

**Issue by evanmcclan** [WirelessRedstoneGroup/WirelessRedstone#199]
Hello. My Server is Running on 1.13.2 with WirelessRedstone Version 3.0.6, Currently the plugin works great except for one problem. When powering a **Transmitter sign** with a button or redstone. It does not activate/ cause the receiver sign to turn into a torch. I can still clikc the transmitter sign or use "/WR A <name>" to activate the receiver, only the redstone power isnt working.
`24.01 15:22:29 [Server] INFO This server is running CraftBukkit version git-Spigot-f56e2e7-98b862a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
24.01 15:22:29 [Server] INFO You are 9 version(s) behind`

Please let me know of any fixes or updates as soon as possible :)

**Comment by Bart-0110** [comment]
Thanks for reporting I'll look into it next week.

**Comment by Bart-0110** [comment]
If anyone has this problem can you try the latest beta?
This should also add basic 1.14 compatibility.

[https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.0-beta.3](https://github.com/WirelessRedstoneGroup/WirelessRedstone/releases/tag/v4.0.0-beta.3)
