### ISSUE TITLE
Button/Lever above WRT sign doesn't work

### ISSUE THREAD

**Issue by James-MStudio** [WirelessRedstoneGroup/WirelessRedstone#214]
I'm using version: 4.0.1
I'm on Minecraft: 1.14
I'm running: Spigot

Seen results:
nothing

Expected results:
activate sign below button/lever

How to reproduce:
![Screenshot_3](https://user-images.githubusercontent.com/44211629/64125510-84f08380-cdaa-11e9-931d-0c4bf679b350.png)

**Comment by Bart-0110** [comment]
Thanks for reporting the issue! Next version should have this fixed.
